path: /apps/DiabloII
appFile: Game.exe
windowTitle: Diablo
hardwareKey: false
appName: DiabloII VN
pageTitle: "Diablo - A Cloud Morph Demo"
appMode: collaborative
discoveryHost: http://discovery.cloudmorph.io
hasChat: true
